language: java

sudo: false
install: true

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.sonar/installs'

addons:
  sonarqube: true

notifications:
  email: false

addons:
  sonarcloud:
    organization: "lequal"
    token:
      secure: sonar-frama-c-plugin-token
# Script to execute.

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar -Dsonar.host.url=https://sonarcloud.io -Dsonar.organization=lequal -Dsonar.login=46053962f3bef0f9ca953d2ffe19aeb93f6c213f
