language: java

sudo: false
install: true

jdk:
  - oraclejdk8

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'
    - '$HOME/.sonar/installs'

addons:
  sonarqube: true

notifications:
  email: false

addons:
  sonarcloud:
    organization: "lequal"
    token:
      secure: 8e949e4df6d60b96cd14527f08228def39e0efd8
# Script to execute.

script:
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent install sonar:sonar 
